name: Build MTProxy for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build MTProxy binary for ARM64
        run: |
          docker buildx build --platform linux/arm64 \
            --output type=local,dest=out .

      - name: Create TAR package
        run: |
          mkdir pkg
          cp out/objs/bin/mtproto-proxy pkg/
          tar -cvf mtproxy-arm64.tar -C pkg mtproto-proxy

      - name: Upload TAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mtproxy-arm64
          path: mtproxy-arm64.tar
